<?php get_template_part('template-parts/sections/home/mt-unica/mt-unica'); ?>
<?php get_template_part('template-parts/sections/home/mt-unica/mt-unica-slide'); ?>
<?php get_template_part('template-parts/sections/home/mt-unica/mt-unica-depoimentos'); ?>
<?php get_template_part('template-parts/sections/home/conheca-beneficios'); ?>
<?php get_template_part('template-parts/sections/home/como-aprender'); ?>
<?php get_template_part('template-parts/sections/home/o-que-dizem'); ?>
<?php get_template_part('template-parts/sections/home/transcender'); ?>
<?php get_template_part('template-parts/sections/home/mundo-melhor'); ?>
<?php get_template_part('template-parts/sections/home/visite-blog'); ?>
<?php get_template_part('template-parts/sections/home/agende-palestra'); ?>
